name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: terminal
          filename: metrics.terminal.svg
          base: header, metadata
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Istanbul
          config_padding: 20
          optimize: svg
          experimental_features: --optimize-svg
          
          
  
